### ISSUE TITLE
Filtro fecha selection

### ISSUE THREAD

**Issue by ElFerdi7** [rafaelaznar/gesane-client#42]
Falta poner el filtro para fechas en la plantilla de los selection para las tablas que contengan fechas.

**Comment by ElFerdi7** [comment]
<option value="2">Filtrar por fecha</option>

 <div ng-show="filterType == 2">
                                    <plistfilterbydatespa                                     
                                        fields="filterDate"
                                        rpp="rpp"
                                        numpage="numpage"
                                        orderparams="orderParams"
                                        filterparams="filterParams">
                                    </plistfilterbydatespa>
                                </div>

**Comment by rafaelaznar** [comment]
Resuelto por fernando martin
